version: "2"
services:
  log-monitoring-target:
    build:
      context: .
    image: log-monitoring-target:latest
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=America/Toronto
      - DEBUG_MODE=0
      - LOOP_TIME=1
      - PORT=8081
      - ID=0
    volumes:
      - /var/lib/docker:/var/lib/docker
      - /mnt/g:/mnt/g
      - /dev/sda
      - /dev/sdb
    network_mode: host
    privileged: true
    command: ["python", "main.py"]
